# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_timestamp', models.DateTimeField(auto_now=True)),
                ('error_code', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=30)),
                ('responsible_account', models.CharField(max_length=50)),
                ('schedule', models.DurationField()),
                ('last_status', models.SmallIntegerField()),
                ('first_checked', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Site'),
        ),
    ]
